# .yarnrc.yml

packageExtensions:
  "pathname@*":
    peerDependenciesMeta:
      node:
        optional: true

enableImmutableInstalls: false
nodeLinker: node-modules

build:
  commands:
    - corepack enable
    - corepack prepare yarn@4.12.0 --activate
    - yarn install
